spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/store
    username: root
    password: root
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    schemas:
    baseline-on-migrate: true
  application:
    name: service-product
logging:
  level:
    org.springframework.web: ERROR
    com.mkyong: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss}[%thread]%-5level %logger{36} - %msg%n"
  file: productlogs.log
server:
  port: 7832
